version: '3.7'
services:
  gui:
    container_name: gui
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - 80:80
    volumes:
      - './nginx:/etc/nginx'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=prod
  api:
    container_name: api
    environment:
      - NODE_ENV=prod
    volumes:
      - './config:/usr/src/app/.config'
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production