version: '3.7'
volumes:
   nginx-config:
      driver: local
services:
  gui:
    container_name: gui
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=dev
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=dev
    volumes:
      - './.config:/usr/src/app/.config'
  nginx:
    image: nginx:latest
    volumes:
      - './nginx.dev:/etc/nginx'
    ports:
      - 80:80
    extra_hosts:
      - localhost:192.168.65.2