version: '3'
volumes:
   etc:

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - etc:/etc
    ports:
      - 80:80
    extra_hosts:
      - localhost:192.168.65.2
